### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by eko24ive** [kramarmm/Homework_6#1]
Please remove padding between elements.
Only first and last navigation element should have rounded edges, use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22926906/44bd184e-f2b7-11e6-8088-e176b27b221e.png)

**Comment by kramarmm** [comment]
Fixed
https://github.com/kramarmm/Homework_6/commit/13bc823f0aa7d99c597404a3a2d29827f4eaa281

**Comment by eko24ive** [comment]
Nice !
